setwd("/home/yujin/Documents/Analyse_triplicats/results/Hclust/2_groups/")
group2=read.table("analyse_paires_2_groups")
setwd("/home/yujin/Documents/Analyse_triplicats/results/Hclust/3_groups/")
group3=read.table("analyse_paires_3_groups")
setwd("/home/yujin/Documents/Analyse_triplicats/results/Hclust/4_groups/")
group4=read.table("analyse_paires_4_groups")
setwd("/home/yujin/Documents/Analyse_triplicats/results/Hclust/5_groups/")
group5=read.table("analyse_paires_5_groups")
setwd("/home/yujin/Documents/Analyse_triplicats/results/Hclust/7_groups/")
group7=read.table("analyse_paires_7_groups")
setwd("/home/yujin/Documents/Analyse_triplicats/results/Hclust/10_groups/")
group10=read.table("analyse_paires_10_groups")

group2_data=subset(group2,group2[,3]!=group2[,4])
group3_data=subset(group3,group3[,3]!=group3[,4])
group4_data=subset(group4,group4[,3]!=group4[,4])
group5_data=subset(group5,group5[,3]!=group5[,4])
group7_data=subset(group7,group7[,3]!=group7[,4])
group10_data=subset(group10,group10[,3]!=group10[,4])


setwd("/home/yujin/Documents/Analyse_triplicats/results/Hclust/2_groups/")
write.table(group2_data,"paires_patrons_différents(2_groups)",quote=F,row.names = F,col.names = F,sep = "\t")
setwd("/home/yujin/Documents/Analyse_triplicats/results/Hclust/3_groups/")
write.table(group3_data,"paires_patrons_différents(3_groups)",quote=F,row.names = F,col.names = F,sep = "\t")
setwd("/home/yujin/Documents/Analyse_triplicats/results/Hclust/4_groups/")
write.table(group4_data,"paires_patrons_différents(4_groups)",quote=F,row.names = F,col.names = F,sep = "\t")
setwd("/home/yujin/Documents/Analyse_triplicats/results/Hclust/5_groups/")
write.table(group5_data,"paires_patrons_différents(5_groups)",quote=F,row.names = F,col.names = F,sep = "\t")
setwd("/home/yujin/Documents/Analyse_triplicats/results/Hclust/7_groups/")
write.table(group7_data,"paires_patrons_différents(7_groups)",quote=F,row.names = F,col.names = F,sep = "\t")
setwd("/home/yujin/Documents/Analyse_triplicats/results/Hclust/10_groups/")
write.table(group10_data,"paires_patrons_différents(10_groups)",quote=F,row.names = F,col.names = F,sep = "\t")
