setwd("/home/yujin/Documents/FPKM/analyse/Hclust/2_groups/")
group2=read.table("analyse_paires_2_groups")
setwd("/home/yujin/Documents/FPKM/analyse/Hclust/3_groups/")
group3=read.table("analyse_paires_3_groups")
setwd("/home/yujin/Documents/FPKM/analyse/Hclust/4_groups/")
group4=read.table("analyse_paires_4_groups")
setwd("/home/yujin/Documents/FPKM/analyse/Hclust/5_groups/")
group5=read.table("analyse_paires_5_groups")
setwd("/home/yujin/Documents/FPKM/analyse/Hclust/8_groups/")
group8=read.table("analyse_paires_8_groups")

group2_data=subset(group2,group2[,3]!=group2[,4])
group3_data=subset(group3,group3[,3]!=group3[,4])
group4_data=subset(group4,group4[,3]!=group4[,4])
group5_data=subset(group5,group5[,3]!=group5[,4])
group8_data=subset(group8,group8[,3]!=group8[,4])

setwd("/home/yujin/Documents/FPKM/test/")

write.table(group2_data,"paires_patrons_différents(2_groups)",quote=F,row.names = F,col.names = F,sep = "\t")
write.table(group3_data,"paires_patrons_différents(3_groups)",quote=F,row.names = F,col.names = F,sep = "\t")
write.table(group4_data,"paires_patrons_différents(4_groups)",quote=F,row.names = F,col.names = F,sep = "\t")
write.table(group5_data,"paires_patrons_différents(5_groups)",quote=F,row.names = F,col.names = F,sep = "\t")
write.table(group8_data,"paires_patrons_différents(8_groups)",quote=F,row.names = F,col.names = F,sep = "\t")
